en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Company Name. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Zapotec Resource Hub"
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/help/"
    ### calls to action ###
    main_cta:
      text: "Login"
      link: "/login/"
    footer_cta:
      text: "Login"
      link: "/login/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about-us/"
      weight: 1
    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 2
    - identifier: "demo-page"
      name: "Demo Page"
      url: "/demo-page/"
      weight: 3
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    - identifier: "contact"
      name: "Contact Us"
      url: "/contact/"
      weight: 5
es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  params:
    description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "acerca-de"
      name: "Acerca de"
      url: "/acerca-de/"
      weight: 1
    - identifier: "faq"
      name: "FAQs"
      url: "/faq-es/"
      weight: 3
    - identifier: "contacto"
      name: "Contacto"
      url: "/contacto/"
      weight: 2
